### ISSUE TITLE
yarnのバージョン設定をどこで行うか？

### ISSUE THREAD

**Issue by unknown-neko** [unknown-neko/unknown-neko.github.io#6]

**Comment by unknown-neko** [comment]
GitHub Actionsのデプロイのジョブに含める

**Comment by unknown-neko** [comment]
node.jsのcorepack enable等で行う

### ローカル側
```
# 管理者権限で
corepack enable
corepack use yarn@*
```

### GitHubAction側
```
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"
          corepack-enable: true
          cache: "yarn"
```
